#!/bin/sh
# postrm script for graylog2-server
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

[ -f /etc/default/graylog2-server ] && . /etc/default/graylog2-server
[ -z "${LOG_DIR}" ] && LOG_DIR="/var/log/graylog2-server"
[ -z "${CONF_DIR}" ] && CONF_DIR="/etc/graylog2-server"


case "${1}" in
    remove)
        # Remove logs
        rm -rf "${LOG_DIR}"
    ;;

    purge)
        # Remove service
        update-rc.d graylog2-server remove >/dev/null || true

        # Remove logs
        rm -rf "${LOG_DIR}"

        # Remove user/group
        deluser graylog2-server || true
        delgroup graylog2-server || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do
    ;;

    *)
        echo "${0} called with unknown argument \`${1}'" >&2
        exit 1
    ;;
esac

exit 0
